---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    run: user-service
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    run: user-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: user-service
    spec:
      containers:
        - name: user-service
          image: gcr.io/k8s-example/user-service:latest
          imagePullPolicy: IfNotPresent # pull local images
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
